### ISSUE TITLE
GraphFromCoo triggers missing numpy dtype 'ulong'

### ISSUE THREAD

**Issue by castagninojose** [networkit/networkit#1368]
---
Description
---

I was trying to create a `nk.Graph` using a scipy coo_matrix and encountered the following issue.

Numpy complaints that there's no `np.ulong`.

A quick google search showed me that this type was indeed removed as of numpy `1.25`.

I tried replacing `np.ulong` with `np.ulonglong` (which _is available_ for my version of numpy) in the `graph.pyx` file, but the issue persists, so probably other places require updating too, or even something else entirely. It may be that this is an easy fix, but I was unable to find other references to 'ulong'.

---
Reproducing
---
Should be straightforward; running the following

```
import networkit as nk
import scipy.sparse as sp
A = sp.coo_matrix([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
nk.graph.GraphFromCoo(A)
```
raises the error
```
File /usr/local/lib/python3.11/dist-packages/networkit/graph.pyx:1192, in networkit.graph.GraphFromCoo()

File /usr/local/lib/python3.11/dist-packages/networkit/graph.pyx:460, in networkit.graph.Graph.addEdges()

File /usr/local/lib/python3.11/dist-packages/numpy/__init__.py:333, in __getattr__(attr)
    330     "Removed in NumPy 1.25.0"
    331     raise RuntimeError("Tester was removed in NumPy 1.25.")
--> 333 raise AttributeError("module {!r} has no attribute "
    334                      "{!r}".format(__name__, attr))

AttributeError: module 'numpy' has no attribute 'ulong'
```
---
Environment info
---
- Python: 3.11.0
- Numpy: 1.26.4
- NetworKit: 11.1.post1

My apologies in advance if this case was already considered/documented.

**Comment by fabratu** [comment]
Hi,

one way to avoid this issue is to use NumPy >= 2.0. Here, `np.ulong` is present (as we also test in our code).

However, by looking at your issue, it became clear that array sizes in numpy/scipy are signed integers anyway. This makes `astype` effectively copy the input data when calling `GraphFromCoo`. I created a PR, changing the internal data types and using views, trying to avoid copies.

With the PR, your code also works with numpy 1.26.4 (`np.ulong` is exchanged either to `np.int32` or `np.int64`).

**Comment by castagninojose** [comment]
Hi, thanks for your response.

It did not occur to me to upgrade (if anything I would've downgraded lol). Definitely could have avoided this by reading numpy docs.

In any case, I am happy to see that changes to keep retro compatibility are being worked on, because I make heavy use of numpy and I think there's a low chance that the change would be painless.

Thank you for your work on this library, it's a great resource.
